## Fundamentals of TensorFlow

To do list:
* Introduction to tensors
* Getting info from tensors
* Manipulating tensors
* Tensors and NumPy
* Using @tf.function ( speed up regular python function )
* Using GPUs with TensorFlow
* Exercises


For accessing the docstring, press Ctrl+Shift+space

## Introduction to Tensors

In [ ]:
# Improt tensorflow
import tensorflow as tf
print(tf.__version__)

2.18.0


In [ ]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

The value for the scalar ndim is 0 since the shape has no values

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

The value for the vector ndim is 1 since the shape has one value

In [ ]:
matrix = tf.constant([[10, 7],
                     [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

The value for the matrix ndim is 2 since the shape has two value

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16) # specify the data type with parameter
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

The value for the another_matrix ndim is 2 since the shape has two elements

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[7, 8, 9],
                       [10, 11, 12]],
                       [[13, 14, 15],
                        [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

(3,2,3) - 3 rows, 2 elements in each, 3 values inside each

In [ ]:
tensor.ndim

3

 Definitions:
 * Scalar: a single number
 * Vector: a number with direction (e.g. wind and speed)
 * Matrix: a 2 dimensional array of numbers
 * Tensor: an n-dimensional array of numbers ( when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

## Creating tensors with `tf.Variable()`

In [ ]:
# Create the same tensor as above
var_tensor = tf.Variable([10,7])
non_variable_tensor = tf.constant([10,7])
var_tensor, non_variable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Try and change one of the element in the changeable tensor
# var_tensor[0] = 7
# var_tensor

In [ ]:
# Using .assign()
var_tensor[0].assign(7)
var_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# # Trying to change unchangeable tensor
# non_variable_tensor[0].assign(7)
# non_variable_tensor

### Creating random tensors
Random tensors are tensors of some arbitrary size which contain random numbers.

In [ ]:
# Create two random (but the same using seed) tensors
random1 = tf.random.Generator.from_seed(42)
random2 = tf.random.Generator.from_seed(42)
random1, random2

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7f6a48ec5690>,
 <tensorflow.python.ops.stateful_random_ops.Generator at 0x7f6a48ebb950>)

In [ ]:
random1 = random1.normal(shape=(3,2))
random2 = random2.normal(shape=(3,2))
random1, random2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

### Shuffle the orders of elements in a tensor


In [ ]:
# Shuffle a tensor (valuable for when we want to shuffle our data so that the inherent order doesn't affect learning)
non_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(non_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Seed inside shuffle will still give different outputs
tf.random.shuffle(non_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [ 3,  4],
       [10,  7]], dtype=int32)>

> "4. If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

Because, "Operations that rely on a random seed actually derive it from two seeds: the global and operation-level seeds. This sets the global seed."



In [ ]:
# Replicate the shuffle of our non-shuffled tensor
tf.random.set_seed(42) # global seed
tf.random.shuffle(non_shuffled, seed=42) # operational level seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other ways to make tensors

In [ ]:
# Create a tensors of all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy array into tensors
Difference: Tensors can be run on a GPU computing

In [ ]:
# Turn NumPy arrays into tensors
import numpy as np
numpy_A = (np.arange(1, 25, dtype=np.int32)) # create a numpy array between 1 and 25
# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non capital for vector

In [ ]:
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A, shape=(2,3,4))
A

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
# The shape must match the number of elements
# 1-25: 24 elements
# shape= 2*3*4 = 24, which equals so it works

### Getting info from tensors
* Shape: The length (number of elements) of each of the dimensions of a tensor.
* Rank: The number of tensor dimensions. A scalar has rank 0, a vector has rank 1, a matrix is rank 2, a tensor has rank n.
* Axis or Dimension: A particular dimension of a tensor.
* Size: The total number of items in the tensor.

In [ ]:

# rank_4_tensor = tf.constant([[[1, 2],
#                             [3, 4]],
#                              [[5, 6],
#                              [7, 8]]])
rank_tensor = tf.constant([[1,2,3,4],[3,4,5,6],[5,6,7,8],[7,8,9,0]])
rank_tensor.ndim

2

In [ ]:
# Create a rank 4 tensor
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor[0][0]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes of our tensors
print("Dataype of element:", rank_4_tensor.dtype)
print("Number of dimensions(rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Element along the 0 axis:", rank_4_tensor.shape[0])
print("Element along the last axis:", rank_4_tensor.shape[-1])
print("Total num of elements:", tf.size(rank_4_tensor))
print("Total num of elements:", tf.size(rank_4_tensor).numpy())

Dataype of element: <dtype: 'float32'>
Number of dimensions(rank): 4
Shape of tensor: (2, 3, 4, 5)
Element along the 0 axis: 2
Element along the last axis: 5
Total num of elements: tf.Tensor(120, shape=(), dtype=int32)
Total num of elements: 120


### Indexing tensors
Tensors can be indexed like python lists


In [ ]:
# Get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element from each dimension from each index except for the final one
rank_4_tensor[:1,:1,:1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
# Create a rank 2 tensor
rank_2_tensor = tf.constant([[10,7],
                            [3,4]])
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Get last item of each row
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
# the dots are the axis before the end axis which we are inserting (newaxis) same as [:,:, tf.newaxis]
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=0) # -expand the 0 axis

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Manipulating tensors (tensor operations)
**Basic operations**
`+`, `-`, `/`, `*`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7],
                      [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor remains unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# We can use tensorflow built-in functions too
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

## Matrix Multiplication
In ML, matrix multiplicaton is one of the most common operations

In [ ]:
# Matrix Multiplication in tensorflow
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# Matrix Multiplication in tensorflow with "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# To reshape: flips acc to our shape
tf.reshape(tensor, shape=(1,4)) # Since 4 elements are there, you can only do it  with 1,4 or 4,1

<tf.Tensor: shape=(1, 4), dtype=int32, numpy=array([[10,  7,  3,  4]], dtype=int32)>

In [ ]:
# Transpose: flips the axes
tf.transpose(tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  3],
       [ 7,  4]], dtype=int32)>

**The dot product**
* tf.matmul()
* tf.tensordot()

In [ ]:
# Perform the matrix multiplication using tensordot
X = tf.constant([[1, 2],
                 [3, 4],
                 [5, 6]])

# Create another (3, 2) tensor
Y = tf.constant([[7, 8],
                 [9, 10],
                 [11, 12]])
tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
tf.tensordot(X, tf.transpose(Y), axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(X, tf.reshape(Y, shape=(2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

### Changing the datatype of the tensor

In [ ]:
# Create a new tensor with default data type (float32)
A = tf.constant([3, 4])
B = tf.constant([1.7, 7.4])
A.dtype, B.dtype


(tf.int32, tf.float32)

In [ ]:
# Change from float32 to float16 (reduced precision)
B = tf.cast(B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

In [ ]:
# Change from int32 to float32
D = tf.cast(A, dtype=tf.float32)
D

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([3., 4.], dtype=float32)>

### Aggregating tensors
condensing them from multiple values down to a smaller amount of values

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Forms of Aggregation:
* Min
* Max
* Sum
* Mean

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
E = tf.constant(np.random.randint(0, 100, size=50))
E
tf.size(E), E.shape, E.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
# Min
print(tf.reduce_min(E))
# Max
print(tf.reduce_max(E))
# Mean
print(tf.reduce_mean(E))
# Sum
print(tf.reduce_sum(E))
E

tf.Tensor(5, shape=(), dtype=int64)
tf.Tensor(99, shape=(), dtype=int64)
tf.Tensor(52, shape=(), dtype=int64)
tf.Tensor(2642, shape=(), dtype=int64)


<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([46, 23,  5, 29, 68, 51, 85,  9, 28, 77,  5, 51,  5, 42, 58, 51, 99,
       35, 41,  7, 66, 17, 44, 78, 60, 34, 15, 87, 76,  7, 68, 65, 90, 57,
       38, 65, 92, 35, 72, 56, 87, 89, 82, 61, 91, 83, 44, 59, 50, 59])>

In [ ]:
import tensorflow_probability as tfp
# Find variance and S.D
print(tfp.stats.variance(E))
print(tf.math.reduce_std(tf.cast(E, dtype=tf.float32)))


tf.Tensor(714, shape=(), dtype=int64)
tf.Tensor(26.723295, shape=(), dtype=float32)


### Find the positional maximum and minimum


In [ ]:
# Create a new tensor for finding the positional max and min
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Max position
print(tf.argmax(F))
# Max value
tf.reduce_max(F)

tf.Tensor(42, shape=(), dtype=int64)


<tf.Tensor: shape=(), dtype=float32, numpy=0.967138409614563>

In [ ]:
# Min position
print(tf.argmin(F))
# Min value
tf.reduce_min(F)

tf.Tensor(16, shape=(), dtype=int64)


<tf.Tensor: shape=(), dtype=float32, numpy=0.009463667869567871>

## Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50) )
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
# Remove one dimensional vectors with squeeze
G_squeezed = tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

### One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3]
# One hot encode
tf.one_hot(some_list, depth=4) # Depth is the number of elements present in the list.

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# First row corresponds to 0, second row corresponds to 1.

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, depth=4, on_value="Get a TA", off_value="Get a RA")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'Get a TA', b'Get a RA', b'Get a RA', b'Get a RA'],
       [b'Get a RA', b'Get a TA', b'Get a RA', b'Get a RA'],
       [b'Get a RA', b'Get a RA', b'Get a TA', b'Get a RA'],
       [b'Get a RA', b'Get a RA', b'Get a RA', b'Get a TA']], dtype=object)>

### Squaring, log, square root

In [ ]:
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#tf.sqrt(H) #tf.math.log(H) # Throws an error

In [ ]:
H = tf.cast(H, dtype=tf.bfloat16)

In [ ]:
tf.sqrt(H)

<tf.Tensor: shape=(9,), dtype=bfloat16, numpy=
array([1, 1.41406, 1.73438, 2, 2.23438, 2.45312, 2.64062, 2.82812, 3],
      dtype=bfloat16)>

In [ ]:
tf.math.log(H)

<tf.Tensor: shape=(9,), dtype=bfloat16, numpy=
array([0, 0.691406, 1.10156, 1.38281, 1.60938, 1.78906, 1.94531, 2.07812,
       2.20312], dtype=bfloat16)>

### Tensors and numpy
Tensorflow interacts seamlessly with NumPy arrays.


In [ ]:
# Create a tensor directly from NumPy array
J = tf.constant(np.array([3., 7., 10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert it back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert a tensor to a Numpy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Default types of each are different
numpy_J = tf.constant(np.array([3., 7., 10.]))
tensor_J = tf.constant([3., 7., 10.])
# Check the data type of each
numpy_J.dtype, tensor_J.dtype

(tf.float64, tf.float32)

In [ ]:
tf.config.list_physical_devices

<function tensorflow.python.framework.config.list_physical_devices(device_type=None)>

In [ ]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found
